#ifndef KEYBOARD_H
#define KEYBOARD_H

enum Scancode {
    ERROR = 0x0,    
    ESC,      
    ONE,      
    TWO,      
    THREE,    
    FOUR,     
    FIVE,     
    SIX,      
    SEVEN,    
    EIGHT,    
    NINE,     
    ZERO,     
    MINUS,    
    PLUS,     
    BACKSPACE,
    TAB,      
    Q,        
    W,        
    E,        
    R,        
    T,        
    Y,        
    U,        
    I,        
    O,        
    P,        
    BRACE_OPEN,
    BRACE_CLOSE,
    ENTER,    
    LEFT_CTRL,
    A,       
    S,       
    D,       
    F,       
    G,       
    H,       
    J,       
    K,       
    L,       
    SEMICOLON,        
    SINGLE_QUOTE,
    TILDA,
    LEFT_SHIFT,
    BACK_SLASH,
    Z,       
    X,        
    C,        
    V,        
    B,        
    N,        
    M,        
    COMMA,    
    PERIOD,   
    FORWARD_SLASH,
    RIGHT_SHIFT,  
    ASTERISK,
    LEFT_ALT,     
    SPACE
};

void keyboard_init();

#endif